### ISSUE TITLE
在Activity Context片段内容重复

### ISSUE THREAD

**Issue by Mrxxy** [leibing8912/AndroidCommonBug#1]
在`Activity Context 的不正确使用`内容中，问题描述与解决方案 代码完全相同

**Comment by leibing8912** [comment]
不一样哦，你观察不够仔细哦，解决方案里面用getApplicationContext()去拿application的context去获取资源，这样就算资源是静态的引用，也没关系，之前是隐式的通过activity的Context去资源，这样静态资源就保存着activity的引用，这样activity就内存泄漏了。

**Comment by Mrxxy** [comment]
我的锅，不好意思哈
